name: Block Pull Request on Stage if Dev Branch Doesn't Have Same Code

on:
  pull_request:
    branches:
      - stage

jobs:
  check_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install requests
      
      - name: Run Python script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python block_pr.py
