stages:
  - check_code
 
check_code:
  stage: check_code
  script:
    - git fetch origin
    - git checkout $CI_COMMIT_REF_NAME
    - git checkout $CI_DEFAULT_BRANCH
    - git diff --exit-code $CI_COMMIT_REF_NAME $CI_DEFAULT_BRANCH || { echo "Code in PR does not match with code in development branch."; exit 1; }
  only:
    - merge_requests
