on:
  push:
    branches:
      - stage

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch dev branch
        run: git fetch origin dev:dev

      - name: Show diff between stage and dev
        run: git diff --name-status dev..stage
