stages:
  - check_code

check_code:
  stage: check_code
  script:
    - git fetch origin $CI_MERGE_REQUEST_TARGET_BRANCH_DEV:$CI_MERGE_REQUEST_TARGET_BRANCH_DEV
    - git checkout $CI_MERGE_REQUEST_TARGET_BRANCH_DEV
    - git diff --name-only origin/$CI_MERGE_REQUEST_TARGET_BRANCH_DEV...$CI_COMMIT_SHA | while read -r FILE; do
        if [ -f "$FILE" ]; then
          git diff origin/$CI_MERGE_REQUEST_TARGET_BRANCH_DEV...$CI_COMMIT_SHA "$FILE" | grep -q "diff --git";
          if [ $? -eq 0 ]; then
            echo "File $FILE contains new changes";
            exit 1; # Fail the pipeline if there are new changes
          fi
        fi
      done
  only:
    - merge_requests
  except:
    - branches

